/*
 * PartBrowser.java
 *
 * Created on 14. Juni 2004, 21:40
 */

package com.kaibla.hamster.util;


import com.kaibla.hamster.collections.BalancedTree;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import javax.swing.JFrame;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**A gui to present a tree of parts.
 *@see Part
 *
 * @author  Kai Orend
 */
public class BalancedTreeBrowser extends javax.swing.JPanel {
    BalancedTree tree=null;
    /** Creates new form PartBrowser */
    public BalancedTreeBrowser(BalancedTree tree) {
        initComponents();
        this.tree=tree;
         LOG.info("Erstelle Baum-Ansicht");
          makeTree(tree.root);
          LOG.info("Erstelle Baum-Ansicht fertig");
        JFrame frame=new JFrame();
        frame.getContentPane().add(this);
        frame.pack();
        frame.show();
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PartTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        PartTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                PartTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(PartTree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    private void PartTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_PartTreeValueChanged

    }//GEN-LAST:event_PartTreeValueChanged
    long last=0;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree PartTree;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    /*F�llt den Baum mit dem root-part.
     */
    DefaultTreeModel model=null;
    public void makeTree(BalancedTree.Entry root) {
        DefaultMutableTreeNode rootnode=new DefaultMutableTreeNode(root);
        model=new DefaultTreeModel(rootnode);
        newNode(rootnode, root);
        PartTree.setModel(model);
    }
    public void newNode(DefaultMutableTreeNode parent, BalancedTree.Entry entry) {
        if(entry==null) {
            return;
        }
        
        if(entry.left!=null) {
            DefaultMutableTreeNode newnode=new DefaultMutableTreeNode(entry.left+" links");
            if(model!=null) {
                model.insertNodeInto(newnode, parent, parent.getChildCount());
            }
            newNode(newnode,entry.left);
        }
        if(entry.right!=null) {
            DefaultMutableTreeNode newnode=new DefaultMutableTreeNode(entry.right+" rechts");
            if(model!=null) {
                model.insertNodeInto(newnode, parent, parent.getChildCount());
            }
            newNode(newnode,entry.right);
        }
    }
    
    /*Soll ein paar parts zum testen erezugen erzeugen.
     *
     */
    private static final Logger LOG = getLogger(BalancedTreeBrowser.class.getName());
    
    
}
